import AppKit
import CoreGraphics
import Foundation

// Render the same cropped Paceman silhouette and expressions as PacemanMark.swift
// into a small LVGL 4bpp font. The watch animates its label, so the bitmap font
// preserves its existing fade, bounce, and sway behavior.
enum Expression: CaseIterable {
    case working, needsInput, finished, failed
}

func rounded(_ rect: CGRect, _ radius: CGFloat) -> CGPath {
    CGPath(roundedRect: rect, cornerWidth: radius, cornerHeight: radius, transform: nil)
}

func bitmap(_ expression: Expression) -> [UInt8] {
    let size = 32
    let context = CGContext(data: nil, width: size, height: size, bitsPerComponent: 8,
                            bytesPerRow: size * 4, space: CGColorSpaceCreateDeviceRGB(),
                            bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue)!
    context.scaleBy(x: CGFloat(size) / 720, y: CGFloat(size) / 720)
    context.translateBy(x: -152, y: -137)
    context.setFillColor(CGColor(gray: 1, alpha: 1))
    context.addPath(rounded(CGRect(x: 232, y: 260, width: 560, height: 448), 154))
    context.fillPath()
    context.fill(CGRect(x: 498, y: 694, width: 28, height: 118))
    context.fillEllipse(in: CGRect(x: 479, y: 779, width: 66, height: 66))
    for x in [162.0, 818.0] {
        context.addPath(rounded(CGRect(x: x, y: 445, width: 44, height: 98), 22))
        context.fillPath()
    }
    context.setBlendMode(.clear)
    switch expression {
    case .working:
        for center in [426.0, 598.0] {
            context.addPath(rounded(CGRect(x: center - 22, y: 445, width: 44, height: 98), 22))
            context.fillPath()
        }
    case .needsInput:
        for center in [426.0, 598.0] {
            let eye = CGMutablePath()
            eye.move(to: CGPoint(x: center - 61, y: 474))
            eye.addLine(to: CGPoint(x: center, y: 543))
            eye.addLine(to: CGPoint(x: center + 61, y: 474))
            eye.addLine(to: CGPoint(x: center + 39, y: 452))
            eye.addLine(to: CGPoint(x: center, y: 497))
            eye.addLine(to: CGPoint(x: center - 39, y: 452))
            eye.closeSubpath()
            context.addPath(eye)
            context.fillPath()
        }
    case .finished:
        for center in [382.0, 642.0] {
            let eye = CGMutablePath()
            eye.move(to: CGPoint(x: center - 65, y: 477))
            eye.addQuadCurve(to: CGPoint(x: center + 65, y: 477),
                             control: CGPoint(x: center, y: 600))
            context.addPath(eye.copy(strokingWithWidth: 31, lineCap: .round,
                                     lineJoin: .round, miterLimit: 10))
            context.fillPath()
        }
    case .failed:
        context.setLineWidth(30)
        context.setLineCap(.round)
        for center in [426.0, 598.0] {
            context.move(to: CGPoint(x: center - 42, y: 536))
            context.addLine(to: CGPoint(x: center + 42, y: 452))
            context.move(to: CGPoint(x: center + 42, y: 536))
            context.addLine(to: CGPoint(x: center - 42, y: 452))
            context.strokePath()
        }
    }
    let image = NSBitmapImageRep(cgImage: context.makeImage()!)
    var nibbles: [UInt8] = []
    for y in 0..<size {
        for x in 0..<size {
            let alpha = image.colorAt(x: x, y: y)!.alphaComponent
            nibbles.append(UInt8((alpha * 15).rounded()))
        }
    }
    return stride(from: 0, to: nibbles.count, by: 2).map {
        (nibbles[$0] << 4) | nibbles[$0 + 1]
    }
}

let names = ["working", "needs input", "finished", "failed"]
var source = """
// Generated by scripts/make-watch-robot-font.swift. Do not edit by hand.
// Private-use glyphs U+E100..U+E103: Paceman working, needs input, finished, failed.
#include "lvgl.h"

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
"""
for (index, expression) in Expression.allCases.enumerated() {
    source += "\n    // U+\(String(format: "%04X", 0xE100 + index)) \(names[index])\n"
    let bytes = bitmap(expression)
    for start in stride(from: 0, to: bytes.count, by: 12) {
        source += "    " + bytes[start..<min(start + 12, bytes.count)]
            .map { String(format: "0x%02x", $0) }.joined(separator: ", ") + ",\n"
    }
}
source += """
};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 0, .adv_w = 512, .box_w = 32, .box_h = 32, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 512, .adv_w = 512, .box_w = 32, .box_h = 32, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1024, .adv_w = 512, .box_w = 32, .box_h = 32, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1536, .adv_w = 512, .box_w = 32, .box_h = 32, .ofs_x = 0, .ofs_y = 0},
};

static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {.range_start = 0xE100, .range_length = 4, .glyph_id_start = 1,
     .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0,
     .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY},
};

static const lv_font_fmt_txt_dsc_t font_dsc = {
    .glyph_bitmap = glyph_bitmap, .glyph_dsc = glyph_dsc, .cmaps = cmaps,
    .kern_dsc = NULL, .kern_scale = 0, .cmap_num = 1, .bpp = 4,
    .kern_classes = 0, .bitmap_format = 0,
};

const lv_font_t paceman_32_agent = {
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = 32, .base_line = 0, .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -5, .underline_thickness = 2,
    .dsc = &font_dsc, .fallback = NULL, .user_data = NULL,
};
"""

try source.write(to: URL(fileURLWithPath: CommandLine.arguments[1]),
                 atomically: true, encoding: .utf8)
